# Hound Configuration
# https://houndci.com/configuration


# Tell GitHub to fail the PR if any violations are found
fail_on_violations: true

# Disable JavaScript checking (jshint)
# Note: We must explicitly disable this (all supported, non-beta languages are reviewed by default)
javascript:
  enabled: false

# Enable ESLint and point to the config file
# Note: Since the ESLint plugin is in beta, we need to explicitly enable
eslint:
  enabled: true
  config_file: .eslintrc

